### ISSUE TITLE
Encrypt LAPS credentials with ansible-vault

### ISSUE THREAD

**Issue by no-12** [ansible-collections/microsoft.ad#100]
##### SUMMARY
It would be nice to have an option to encrypt the LAPS credentials fetched by the ldap inventory plugin with ansible-vault.
This would make storing the LAPS credentials in AWX a little bit more secure and won't allow users with read permissions on the inventory to view the credentials.
This would also be useful if you run this plugin without AWX to generate a "static" inventory file.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
microsoft.ad.ldap inventory

**Comment by jborean93** [comment]
Hi I'm not sure what the benefits of this would be as the LAPS password changes quite frequently and it's not really designed to be stored offline. I'm not 100% familiar with AWX, are you saying that having it run the dynamic inventory allows it to read the generated inventory?

You can use `ansible-inventory` to retrieve the the password details which you then can encrypt if you wish but this is something you have to do everytime the LAPS password is changed. For example I have this inventory configuration at `microsoft.ad.ldap.yml`

```yaml
plugin: microsoft.ad.ldap

search_base: OU=Servers,DC=domain,DC=test

attributes:
  msLAPS-EncryptedPassword:
    ansible_user: (this.value | from_json).n
    ansible_password: (this.value | from_json).p
```

I can run the following to retrieve the username and password configured by LAPS:

```bash
$ ansible-inventory -i microsoft.ad.ldap.yml --host SERVER2022 --vars
```

```json
{
    "ansible_host": "SERVER2022.domain.test",
    "ansible_password": "...",
    "ansible_user": "Administrator",
    "microsoft_ad_distinguished_name": "CN=SERVER2022,OU=Servers,DC=domain,DC=test"
}
