### ISSUE TITLE
Error: Skip computer 'x' with new name 'x' because the new name is the same as the current name.

### ISSUE THREAD

**Issue by aristotelos** [ansible-collections/microsoft.ad#113]
##### SUMMARY
The `microsoft.ad.membership` fails if the computer name is longer than 15 characters.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
microsoft.ad.membership

##### ANSIBLE VERSION

```paste below
2.9.27
```

##### COLLECTION VERSION

```paste below
microsoft.ad:1.5.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Windows 10.

##### STEPS TO REPRODUCE
Join a computer to a domain using the following task. Use a computer name that is longer than 15 characters:

```yaml
    - name: Join AD domain
      microsoft.ad.membership:
        dns_domain_name: "test.local"
        domain_admin_user: "{{ domain_admin_user}}"
        domain_admin_password: "{{ domain_admin_password }}"
        hostname: "my-long-computer-name"
        state: "domain"
        reboot: true
```

##### EXPECTED RESULTS
The step should succeed without changes because of idempotency.

##### ACTUAL RESULTS
```paste below
Run: [2024-04-24 22:56:39,277][INFO][CMD]: TASK [ad-joined : Join AD domain]  **********************************************
Run: [2024-04-24 22:56:42,784][INFO][CMD]: fatal: [workstation] FAILED! => {"changed": false, "msg": "Skip computer 'my-long-computer-name' with new name 'my-long-computer-name' because the new name is the same as the current name.", "reboot_required": false}
Run: [2024-04-24 22:56:42,785][INFO][CMD]: 	to retry, use: --limit @/app/data/playbook.retry
```
