### ISSUE TITLE
New-ADObject failed: The security descriptor is invalid

### ISSUE THREAD

**Issue by david-sieg** [ansible-collections/microsoft.ad#123]
##### SUMMARY

I want to create an Managed Service Account.
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
2.16
```

##### COLLECTION VERSION

```paste below
1.6.0
```

##### STEPS TO REPRODUCE

```yaml

- name: Create Managed Service Accounts
  microsoft.ad.object:
    attributes:
      set:
        msDS-GroupMSAMembership: "SQLSERVER01$"
    name: "183_service"
    path: "CN=Managed Service Accounts,DC=local,DC=ad"
    protect_from_deletion: false
    state: "present"
    type: "msDS-GroupManagedServiceAccount"
    description: "Group Managed Service Account for SQL Server"

```

##### EXPECTED RESULTS

An created managed service account.

##### ACTUAL RESULTS

```paste below
failed: [domain.ad.local] (item={'name': '183_service', 'description': 'Group Managed Service Account for SQL Server ', 'path': 'CN=Managed Service Accounts,DC=local,DC=ad', 'gmsa_members': 'SQLSERVER01$'}) => {
    "ansible_loop_var": "user",
    "changed": false,
    "distinguished_name": null,
    "invocation": {
        "module_args": {
            "attributes": {
                "add": {},
                "remove": {},
                "set": {
                    "msDS-GroupMSAMembership": "SQLSERVER01$"
                }
            },
            "description": "Group Managed Service Account for SQL Server",
            "display_name": null,
            "domain_credentials": [],
            "domain_password": null,
            "domain_server": null,
            "domain_username": null,
            "identity": null,
            "name": "183_service",
            "path": "CN=Managed Service Accounts,DC=local,DC=ad",
            "protect_from_deletion": false,
            "state": "present",
            "type": "msDS-GroupManagedServiceAccount"
        }
    },
    "msg": "New-ADObject failed: The security descriptor is invalid",
    "object_guid": null,
    "user": {
        "description": "Group Managed Service Account for SQL Server)",
        "gmsa_members": "SQLSERVER01$",
        "name": "183_service",
        "path": "CN=Managed Service Accounts,DC=local,DC=ad"
    }
}
```
