### ISSUE TITLE
Moving computer object fails

### ISSUE THREAD

**Issue by jengstrom440** [ansible-collections/microsoft.ad#124]
##### SUMMARY
Moving a computer object does not work per documentation, ansible attempts use New-ADComputer instead of Move-ADObject.

##### ISSUE TYPE
Bug

##### COMPONENT NAME
microsoft.ad.computer

##### ANSIBLE VERSION
ansible [core 2.16.3]
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

##### COLLECTION VERSION
ansible-galaxy collection list microsoft.ad

/home/ansible/.ansible/collections/ansible_collections
Collection   Version
microsoft.ad 1.6.0  

/usr/lib/python3/dist-packages/ansible_collections
Collection   Version
microsoft.ad 1.4.1  

##### CONFIGURATION
CONFIG_FILE() = None

##### OS / ENVIRONMENT
Ubuntu 24.04 Server install on VMware ESXi 8

##### STEPS TO REPRODUCE
I have a simple playbook to move a computer account in AD to a specified OU in the 'path'. Happens each time it is run.

    - name: Move server to Domain Servers OU
      microsoft.ad.computer:
        identity: "{{ ansible_hostname }}"
        path: OU=Domain Servers,OU=Site-Location,DC=ad,DC=cityofgotham,DC=com

##### EXPECTED RESULTS
I expect the existing computer account to be moved and not recreated.  Documentation states that:

**identity:** This must be specified if; name is not set, when trying to rename the object with a new name, _or when trying to move the object into a different path._

  - Documentation states then when moving an object to a new path, identity must be specified. I have specified identity and is reporting computer object name correctly in error output.

**path:** _If managing an existing object found by identity, the path of the found object will be moved to the one specified by this option._ If no path is specified, the object will not be moved.

  - Documentation states that with identity, identified object will move to specified path. Proper path is visible in output.

##### ACTUAL RESULTS
Since it is using "New-ADComputer" in the verbose error output instead of "Move-ADObject", this will not achieve desired results. This needs to be adjusted for "Move-ADObject" instead:

1:53:18 PM
The full traceback is:
1:53:18 PM
The specified account already exists
1:53:18 PM
At line:984 char:29
1:53:18 PM
$adObject = & $newCommand @newParams @adParams
1:53:18 PM

1:53:18 PM
CategoryInfo          : ResourceExists: (CN=batman,O...ofgotham,DC=com:String) [New-ADComputer]

**Comment by david-sieg** [comment]
Hi,

we resolved it with two tasks:

```
- name: "Search computer object in ad to fetch guid [ad_manage_computer_add]"
  microsoft.ad.object_info:
    ldap_filter: "(&(objectClass=computer)(cn={{ inventory_hostname_short }}*))"
    properties: '*'
    domain_server: ADCONTROLLER
    domain_username: ADMIN
    domain_password: PASSWORD
  delegate_to: ADCONTROLLER
  register: reg_computer_obj

- name: "Move computer object to the right Active Directory OU [ad_manage_computer_add]"
  microsoft.ad.object:
    identity: '{{ reg_computer_obj.objects.0.ObjectGUID }}'
    name: "{{ inventory_hostname_short }}"
    path: "CN=Computers,DC=domain,DC=com"
    type: computer
    domain_server: ADCONTROLLER
    domain_username: ADMIN
    domain_password: PASSWORD
    state: present
  delegate_to: ADCONTROLLER
```

Hope that helps...
