### ISSUE TITLE
`microsoft.ad.group` fails with `members.set` set to an empty list on new objects

### ISSUE THREAD

**Issue by briantist** [ansible-collections/microsoft.ad#141]
##### SUMMARY

When using `microsoft.ad.group` to set the members of a group to an empty list (enforce that the group has no members), the underlying call to `New-ADGroup` fails when trying to create the new group. It works properly as long as the group already exists.

This also affects check mode, so if you're creating an object in a previous call and then in a later call trying to add it as a member of a group with this module in check mode, that object may not exist yet. In theory you can use `lookup_failure_action` set to `warn` or `ignore` to work around that, even conditionally on check mode, but if the final list is empty the module call will still fail.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below
Collection   Version
------------ -------
microsoft.ad 1.6.0
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(env: ANSIBLE_FORKS) = 30
```

##### STEPS TO REPRODUCE

```yaml
      microsoft.ad.group:
        # truncated
        members:
          set: []
```

Another thing I tried (also fails):

```yaml
      microsoft.ad.group:
        # truncated
        members:
          set: [fake]
          lookup_failure_action: warn
```
(this results in an empty list internally anyway since the lookup fails and the problem is the same)

##### EXPECTED RESULTS

A new group is created with no members, and subsequent calls will enforce the empty members.

##### ACTUAL RESULTS

```paste below
Cannot validate argument on parameter 'OtherAttributes'. The argument is null or an element of the argument collection contains a null value.
At line:1266 char:43
+                 $adObject = & $newCommand @newParams @adParams
+                                           ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-ADGroup], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.ActiveDirectory.Management.Commands.NewADGroup

ScriptStackTrace:
at Invoke-AnsibleADObject, <No file>: line 1266
at <ScriptBlock>, <No file>: line 84
```

---

# Workarounds

Currently I have two workarounds for different scenarios. In the case of a group that should be empty and may need to be created by ansible I'm using this ugliness:

```yaml
- name: Empty set workaround
  vars:
    set_members: true
    empty_set:
      set: []
    members: '{{ empty_set if set_members else omit }}'
  block:
    - name: Group
      microsoft.ad.group: &group
        # truncated
        members: '{{ members }}'
  rescue:
    - name: Group (first create)
      vars:
        set_members: false
      microsoft.ad.group: *group
```

(it doesn't look so bad in the truncated example but it's kind of a pain and I still have to repeat other keywords like `loop` and `when` and whatever else is on the original module call, also it will rescue on any error in the original module not just the specific error I want to catch)

For the case of referencing previous created objects in check mode, I'm doing this:

```yaml
- name: Account group
  microsoft.ad.group:
    # truncated
    members:
      lookup_failure_action: '{{ "warn" if ansible_check_mode else "fail" }}'
      set: '{{ list_of_accounts_created_in_previous_task }}'
  register: group_status
  failed_when: >-
    group_status is failed and (
      group_status.msg is not search("Cannot validate argument on parameter 'OtherAttributes'. The argument is null or an element of the argument collection contains a null value")
      or not ansible_check_mode
    )
  changed_when: >-
    (
      group_status is changed and not ansible_check_mode
    ) or (
      group_status is failed
      and group_status.msg is search("Cannot validate argument on parameter 'OtherAttributes'. The argument is null or an element of the argument collection contains a null value")
      and ansible_check_mode
    )
```

The `lookup_failure_action: '{{ "warn" if ansible_check_mode else "fail" }}'` should be enough to support check mode in the general case, but because of the empty list issue I need the `register`, `failed_when`, and `changed_when` (for proper changed status) which is a lot of extra junk.
