### ISSUE TITLE
microsoft.ad.user user_cannot_change_password also setting Everyone deny for change password

### ISSUE THREAD

**Issue by Regan-NIWA** [ansible-collections/microsoft.ad#157]
##### SUMMARY

When creating accounts with microsoft.ad.user and setting user_cannot_change_password: true, the account created ends up with 2 Deny permissions. The correct one 'Self: Change password' but also wrongly 'Everyone: Change password'
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

 microsoft.ad.user
##### ANSIBLE VERSION

```paste below
ansible [core 2.15.12]
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.19 (main, Aug 13 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        7.0.0
ansible.posix                            1.5.4
ansible.utils                            5.1.0
ansible.windows                          2.4.0
awx.awx                                  24.6.1
azure.azcollection                       2.6.0
community.crypto                         2.21.1
community.docker                         3.12.1
community.general                        9.3.0
community.library_inventory_filtering_v1 1.0.1
community.vmware                         4.5.0
community.windows                        2.2.0
junipernetworks.junos                    9.1.0
kubernetes.core                          5.0.0
microsoft.ad                             1.6.0
```

##### OS / ENVIRONMENT

Windows Server 2022

##### STEPS TO REPRODUCE

Create an account using  microsoft.ad.user and set user_cannot_change_password: true

```yaml
- name: Create Active Directory Account
  microsoft.ad.user:
    name: "{{ account_name }}"
    display_name: "{{ account_display_name }}"
    sam_account_name: "{{ account_samaccountname }}"
    password: "{{ account_password }}"
    password_never_expires: true
    user_cannot_change_password: true
    update_password: "on_create"
    upn: "{{ account_upn }}@{{ domain }}"
    path: "{{ account_path }}"
    description: "{{ account_description }}"
    domain_username: "{{ ad_user_admin_username }}"
    domain_password: "{{ ad_user_admin_password }}"
    domain_server: "{{ domain }}"
    state: "present"
```

##### EXPECTED RESULTS

![image](https://github.com/user-attachments/assets/a00b8ffc-d630-4e3d-9d8d-dc7f08ca8e92)

##### ACTUAL RESULTS

![image](https://github.com/user-attachments/assets/45a30b1d-6508-4c24-8511-b4a7da043226)
