### ISSUE TITLE
Could we add a parameter to judge whether we need to add an ad user

### ISSUE THREAD

**Issue by IslandsWhite** [ansible-collections/microsoft.ad#172]
##### SUMMARY

I found that if I type in a wrong sAMAccountName when change user's password, this module will create a new user for me. This is not what I want.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml
- name: change password
  microsoft.ad.user:
    identity: "{{ ad_sam }}"
    password: "{{ ad_password }}"
    state: present
```

**Comment by jborean93** [comment]
I think in this case it is designed to manage ad users and not the passwords. Adding an extra option complicates the code as it's not designed for this particular scenario and implementing it requires changes to a share codebase inherited by other modules in this collection.

For your case you can achieve the same thing by using `microsoft.ad.object_info` to check if the user exists or not

```yaml
- name: check if user exists
  microsoft.ad.object_info:
    identity: '{{ ad_sam }}'
  register: user_info

- name: change password
  microsoft.ad.user:
    identity: '{{ user_info.objects[0].ObjectGUID }}'
    password: '{{ ad_password }}'
    state: present
  when: user_info.objects | length == 1
```

**Comment by IslandsWhite** [comment]
Hi there, I tried the microsoft.ad.object_info module, and compared with the official ansible document. It says the 'identity' parameter should be a single Active Directory object by its distinguished name or its object GUID. It will output an empty objects when I use sAMAccountName. The basic information I will get from user is the sAMAccountName. Is there any other module can do this job.

**Comment by jborean93** [comment]
My apologies, I forgot the identity on that module only does the DN or Guid. You can use `ldap_filter` instead of 

```yaml
- name: check if user exists
  microsoft.ad.object_info:
    ldap_filter: sAMAccountName={{ ad_sam }}
  register: user_info
```
