### ISSUE TITLE
microsoft.ad.group remove group member fails to remove the user identified

### ISSUE THREAD

**Issue by clsmith70** [ansible-collections/microsoft.ad#179]
##### SUMMARY
I have set up a template that adds or removes group members from an AD group.  Adding members is working fine, but when trying to remove members from the group, the following error is returned.

`Set-ADGroup failed: A global group cannot have a universal group as a member`

The target group this happened to is a universal group, but it only has user objects as members, no nested groups, and the task was run to remove a user object from the group.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

microsoft.ad.group

##### ANSIBLE VERSION

The following is from the AAP control node.

```bash
ansible [core 2.14.17]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.21 (main, Dec  5 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

The following is from my dev workstation, but the version is the same in the EE container
```paste below
$ ansible-galaxy collection list microsoft.ad

# /home/chris/.ansible/collections/ansible_collections
Collection   Version
------------ -------
microsoft.ad 1.8.0  
```

##### CONFIGURATION

```bash
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

```bash
$ sudo cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.5 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.5"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.5 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://issues.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.5"
```

##### STEPS TO REPRODUCE

A role is used to run the task, excerpt of remove member task configuration is below.
The role is run using an execution environment that includes `microsoft.ad 1.8.0`

```yaml
- name: Get group facts
  register: group_info
  failed_when: group_info is not defined
  microsoft.ad.object_info:
    filter: "sAMAccountName -eq '{{ ad_group_identity }}'"
    properties:
      - groupType
      - name

- name: Set group category and scope
  when: group_info is defined
  ansible.builtin.set_fact:
    groupCategory: "{% if group_info['objects'][0]['groupType'] in ['2', '4', '8'] %}distribution{% else %}security{% endif %}"
    groupScope: "{% if group_info['objects'][0]['groupType'] in ['2', '-2147483646'] %}global{% elif group_info['objects'][0]['groupType'] in  ['4', '-2147483644'] %}domainlocal{% else %}universal{% endif %}"
    groupIdentity: "{{ group_info['objects'][0]['DistinguishedName'] }}"
    groupName: "{{ group_info['objects'][0]['Name'] }}"

- name: Remove group member
  when: 
    - ad_group_update == 'remove_member'
    - group_info is defined
  microsoft.ad.group:
    identity: "{{ groupIdentity }}"
    name: "{{ groupName }}"
    scope: "{{ groupScope }}"
    members:
      remove: "{{ ad_group_member | trim | split('\n') }}"
      lookup_failure_action: warn

```

##### EXPECTED RESULTS

The group member identified by sAMAccountName is removed from the group successfully.

##### ACTUAL RESULTS

When the template is run by staff, the result is a failed job run and the user is still a member of the group.

```paste below
fatal: [REDACTED]: FAILED! => {"changed": false, "distinguished_name": "CN=HR Business Office,OU=...REDACTED...", "msg": "Set-ADGroup failed: A global group cannot have a universal group as a member", "object_guid": "REDACTED"}

```
