### ISSUE TITLE
microsoft.ad.user property "password_expired" does not work.

### ISSUE THREAD

**Issue by hematic** [ansible-collections/microsoft.ad#180]
##### SUMMARY
microsoft.ad.user property "password_expired" does not work.

When setting password_expired: true, users are not forced to change their account at next logon. Verified with over a hundred user accounts.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
microsoft.ad.user

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```
1.8.0

```
##### STEPS TO REPRODUCE

```
- name: Set Password
  microsoft.ad.user:
    identity: "{{ new_joiner }}"
    domain_username: "{{ domain_username }}"
    domain_password: "{{ domain_password }}"
    domain_server: "{{ domain_controller.result }}"
    password: "{{ new_password }}"
    password_expired: true
```

##### EXPECTED RESULTS

Expected that the checkbox on the user account "user must change password at next logon" will be checked.

##### ACTUAL RESULTS

The box is not checked :)

I have edited some sensitive values.
```paste below
{
  "changed": true,
  "invocation": {
    "module_args": {
      "account_locked": null,
      "identity": "USER",
      "postal_code": null,
      "description": null,
      "email": null,
      "groups": null,
      "name": null,
      "state_province": null,
      "upn": null,
      "display_name": null,
      "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "country": null,
      "delegates": null,
      "domain_username": "DOMAIN\\USER",
      "company": null,
      "update_password": "always",
      "city": null,
      "path": null,
      "password_expired": true,
      "sam_account_name": null,
      "password_never_expires": null,
      "street": null,
      "domain_server": "DC",
      "spn": null,
      "enabled": null,
      "user_cannot_change_password": null,
      "attributes": {
        "add": {},
        "set": {},
        "remove": {}
      },
      "firstname": null,
      "state": "present",
      "domain_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "protect_from_deletion": null,
      "surname": null,
      "domain_credentials": []
    }
  },
  "distinguished_name": "DN of USER",
  "object_guid": "GUID OF USER",
  "sid": "SID OF USER",
  "_ansible_no_log": false
}
```

**Comment by jborean93** [comment]
I cannot replicate this, this is the output with a `--diff` to show the option was changed (I also checked that it was unset in the GUI beforehand)

```yaml
--- before
+++ after
@@ -1,6 +1,6 @@
     attributes: {}
     name: TestUser
-    password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
-    password_expired: false
+    password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER - changed
+    password_expired: true
     path: CN=Users,DC=domain,DC=test
 

changed: [DC01] => 
    changed: true
    diff:
        after:
            attributes: {}
            name: TestUser
            password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER - changed
            password_expired: true
            path: CN=Users,DC=domain,DC=test
        before:
            attributes: {}
            name: TestUser
            password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
            password_expired: false
            path: CN=Users,DC=domain,DC=test
    distinguished_name: CN=TestUser,CN=Users,DC=domain,DC=test
    invocation:
        module_args:
            account_locked: null
            attributes:
                add: {}
                remove: {}
                set: {}
            city: null
            company: null
            country: null
            delegates: null
            description: null
            display_name: null
            domain_credentials: []
            domain_password: null
            domain_server: null
            domain_username: null
            email: null
            enabled: null
            firstname: null
            groups: null
            identity: null
            name: TestUser
            password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
            password_expired: true
            password_never_expires: null
            path: null
            postal_code: null
            protect_from_deletion: null
            sam_account_name: null
            spn: null
            state: present
            state_province: null
            street: null
            surname: null
            update_password: always
            upn: null
            user_cannot_change_password: null
    object_guid: 76091b3d-b2a6-4635-b5d9-6e54e5870e08
    sid: S-1-5-21-2100517712-2957671396-2033368311-1137
```

The account options show that `User must change password at next logon` is checked after running the task.

![Image](https://github.com/user-attachments/assets/58444489-fa9c-496e-a7eb-9ac8a347009b)

I also tried it with a combination of `update_password: when_changed` and it would always et the correct property. Are you setting any other options or attributes at the same time?

The code to manage this option is the below.

https://github.com/ansible-collections/microsoft.ad/blob/4bde91e516332144c32e2b1bbc2d1e4b34c070d4/plugins/modules/user.ps1#L211-L225

It adds `-ChangePasswordAtLogon` to `New-ADUser` when creating the account and `-ChangePasswordAtLogon $value` on `Set-ADUser` if the existing value does not reflect the desired option.
