### ISSUE TITLE
delegated managed service account support

### ISSUE THREAD

**Issue by DorBreger** [ansible-collections/microsoft.ad#185]
## Feature Idea
Support  for the new delegated managed service account in windows server 2025
##### COMPONENT NAME

microsoft.ad.service_account

### EXAMPLE

```yaml
- name: Add gMSA with sAMAccountName without $ suffix
  microsoft.ad.service_account:
    identity: MySA
    dns_hostname: MySA.contoso.com
    sam_account_name: MySA
    do_not_append_dollar_to_sam: true
    delegated_account: true

```
