### ISSUE TITLE
Cannot retrieve an encrypted LAPS password

### ISSUE THREAD

**Issue by BITControl-MB** [ansible-collections/microsoft.ad#194]
##### SUMMARY

I am currently trying to read LAPS passwords from our domain using Ansible. The LAPS passwords are stored in encrypted form. I have installed dpapi-ng as described in the documentation. However, I cannot retrieve the username or password. No error message is displayed either.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

microsoft.ad.ldap

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.5]
  config file = /home/user/repos/ansible-repository/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/user/repos/dotnet/semaphore-repository/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] (/home/user/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/user/repos/ansible-repository/collections/ansible_collections
Collection   Version
------------ -------
microsoft.ad 1.9.0 
```

##### CONFIGURATION

Ansible configuration:
```paste below
COLLECTIONS_PATHS(/home/user/repos/ansible-repository/ansible.cfg) = ['/home/user/repos/ansible-repository/collections']
CONFIG_FILE() = /home/user/repos/ansible-repository/ansible.cfg
DEFAULT_GATHERING(/home/user/repos/ansible-repository/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/user/repos/ansible-repository/ansible.cfg) = ['/home/user/repos/ansible-repository/inventories']
DEFAULT_ROLES_PATH(/home/user/repos/ansible-repository/ansible.cfg) = ['/home/user/repos/ansible-repository/roles']
```

Inventory file:
```yaml
plugin: microsoft.ad.ldap

server: DC01.example.local
tls_mode: ldaps
username: Administrator@EXAMPLE.LOCAL
password: xxxxxxx
auth_protocol: kerberos
ca_cert: /etc/ssl/certs/example-DC01-CA.cer
search_base: OU=Testrechner,DC=example,DC=local

attributes:
  msLAPS-EncryptedPassword:
    ansible_user: (this.value | from_json).n
    ansible_password: (this.value | from_json).p
    raw_example: raw
    this_example: this
```

##### OS / ENVIRONMENT

Operating System: Debian GNU/Linux 12.11 (bookworm)        
Kernel: Linux 6.1.0-35-amd64

Installed libraries (output of the command `ansible localhost -m microsoft.ad.debug_ldap_client`):
```yaml
localhost | SUCCESS => {
    "changed": false,
    "dns": {
        "default_port": 389,
        "default_server": "dc01.example.local",
        "exception": null,
        "records": [
            {
                "port": 389,
                "priority": 0,
                "target": "dc01.example.local.",
                "weight": 100
            },
            {
                "port": 389,
                "priority": 0,
                "target": "DC02.example.local.",
                "weight": 100
            }
        ]
    },
    "kerberos": {
        "default_cc": {
            "creds": [
                {
                    "client": "Administrator@EXAMPLE.LOCAL",
                    "server": "krbtgt/EXAMPLE.LOCAL@EXAMPLE.LOCAL"
                }
            ],
            "exception": null,
            "name": "FILE:/tmp/krb5cc_318001653",
            "principal": "Administrator@EXAMPLE.LOCAL"
        },
        "default_realm": "EXAMPLE.LOCAL",
        "exception": null
    },
    "packages": {
        "dnspython": "2.7.0",
        "dpapi_ng": "0.2.0",
        "krb5": "0.7.1",
        "pyspnego": "0.11.2",
        "sansldap": "0.1.0"
    }
}
```

##### STEPS TO REPRODUCE

I have executed the following command from the [examples ](https://docs.ansible.com/ansible/latest/collections/microsoft/ad/docsite/guide_ldap_inventory.html#ansible-collections-microsoft-ad-docsite-guide-ldap-inventory-laps) in the documentation:

```yaml
ansible-inventory -i ./inventories/staging/microsoft.ad.ldap.yml --host BC-DT05 --vars --yaml -vvvv
```

##### EXPECTED RESULTS

I expected to receive the LAPS password in plain text, as described in the example. The output should have been similar to this:
```yaml
ansible_host: BC-DT05.example.local
ansible_password: xxxxxxxx
ansible_user: Administrator
microsoft_ad_distinguished_name: CN=BC-DT05,OU=Testrechner,DC=example,DC=local
raw_example:
- xxxxxx...
this_example:
  encrypted_value: xxxxx...
  flags: 0
  info: ''
  update_timestamp: 133281382308674404
  value: '{"n":"Administrator","t":"1d982b607ae7b64","p":"xxxxxxx"}'
```

##### ACTUAL RESULTS

When I execute the command `ansible-inventory -i ./inventories/staging/microsoft.ad.ldap.yml --host BC-DT05 --vars --yaml -vvvv`, I only get the following output:

```paste below
ansible-inventory [core 2.18.5]
  config file = /home/user/repos/ansible-repository/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/user/repos/ansible-repository/collections
  executable location = /home/user/.local/bin/ansible-inventory
  python version = 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] (/home/user/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.6
  libyaml = True
Using /home/user/repos/ansible-repository/ansible.cfg as config file
setting up inventory plugins
Loading collection ansible.builtin from 
host_list declined parsing /home/user/repos/ansible-repository/inventories/staging/microsoft.ad.ldap.yml as it did not pass its verify_file() method
script declined parsing /home/user/repos/ansible-repository/inventories/staging/microsoft.ad.ldap.yml as it did not pass its verify_file() method
Loading collection microsoft.ad from /home/user/repos/ansible-repository/collections/ansible_collections/microsoft/ad
Using inventory plugin 'ansible_collections.microsoft.ad.plugins.inventory.ldap' to process inventory source '/home/user/repos/ansible-repository/inventories/staging/microsoft.ad.ldap.yml'
Parsed /home/user/repos/ansible-repository/inventories/staging/microsoft.ad.ldap.yml inventory source with auto plugin
ansible_host: BC-DT05.example.local
microsoft_ad_distinguished_name: CN=BC-DT05,OU=Testrechner,DC=example,DC=local
raw_example:
- xxxxxx...
```
Username and password are not returned and the `this_example` part is also completely missing. According to the example, there should be a debug attribute here if an error occurs.
