### ISSUE TITLE
microsoft.ad.group module fails to add member to existing group

### ISSUE THREAD

**Issue by sigveo** [ansible-collections/microsoft.ad#196]
##### SUMMARY

When trying to add a computer to an existing Active Directory group, the play fails with error "New-ADGroup failed: The specified group already exists"
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

microsoft.ad.group module
##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Windows server 2025

##### STEPS TO REPRODUCE

```yaml
- name: Define name of computer to be added to group
  ansible.builtin.set_fact:
    group_member: "{{ ansible_netbios_name }}$"

- name: Add computer to group in AD
  microsoft.ad.group:
    name: "{{ existing_group_name }}"
    scope: global
    members:
      add:
        - "{{ group_member }}"
    domain_username: "{{ domain_username }}"
    domain_password: "{{ domain_user_password }}"
  delegate_to: "{{ management_server_with_ActiveDirectory_module }}"
```

##### EXPECTED RESULTS
The computer to be added to the active directory group while preserving existing members

##### ACTUAL RESULTS

Fails with error "New-ADGroup failed: The specified group already exists"

```paste below

```

**Comment by jborean93** [comment]
Please keep in mind that `name` is not the `sAMAccountName` of a group but rather the LDAP `cn` of the group in a path specified. The docs of [microsoft.ad.group name state](https://docs.ansible.com/ansible/latest/collections/microsoft/ad/group_module.html#parameter-name)

> The name of the AD object to manage, this is not the sAMAccountName of the object but the LDAP cn or name entry of the object in the path specified. Use identity to select an object to manage by its sAMAccountName.

If you are trying to add a member to a group that already exists but don't know the LDAP path the group is part of, use the `identity` parameter instead as that will lookup the group by `sAMAccountName` instead.

**Comment by Yannik** [comment]
@jborean93 I actually just ran into a very similar/identical issue.

Execute the following task twice:
```
    - microsoft.ad.group:
        name: mygroup@example.net
        path: "cn=Users,dc=example,dc=net"
        scope: global
```
...and the second task execution will fail with the error mentioned by OP:
```
TASK [microsoft.ad.group] ******************************************************************************************************************************************
fatal: [dc1]: FAILED! => changed=false 
  distinguished_name: null
  msg: 'New-ADGroup failed: The specified group already exists'
  object_guid: null
```

This shall not fail because the identity should be automatically constructed from name and path according to the docs:

> If omitted, the AD object to manage is selected by the distinguishedName using the format CN={{ name }},{{ path }}. If path is not defined, the defaultNamingContext is used instead.

Further testing shows that this error occurs even when explicitly setting identity to the groups DN.

I believe this might an issue with the `@`-symbol, since this issue does NOT occur for a `name` of just `mygroup` instead of` mygroup@example.net`. 

(In OPs case no path is given and we do not know if the object is in defaultNamingContext or elsewhere - neither do we know about the actual name of the group - feel free to elaborate on that @sigveo).
