### ISSUE TITLE
microsoft.ad.group tries to re-create existing groups when they contain @ in name

### ISSUE THREAD

**Issue by Yannik** [ansible-collections/microsoft.ad#198]
##### SUMMARY

Execute the following task twice:
```
    - microsoft.ad.group:
        name: mygroup@example.net
        path: "cn=Users,dc=example,dc=net"
        scope: global
```
...and the second task execution will fail with the error mentioned by OP:
```
TASK [microsoft.ad.group] ******************************************************************************************************************************************
fatal: [dc1]: FAILED! => changed=false 
  distinguished_name: null
  msg: 'New-ADGroup failed: The specified group already exists'
  object_guid: null
```

This shall not fail because the identity should be automatically constructed from name and path according to the docs:

> If omitted, the AD object to manage is selected by the distinguishedName using the format CN={{ name }},{{ path }}. If path is not defined, the defaultNamingContext is used instead.

Further testing shows that this error occurs even when explicitly setting identity to the groups DN.

I believe this might an issue with the `@`-symbol, since this issue does NOT occur for a `name` of just `mygroup` instead of` mygroup@example.net`. 

This occurs on microsoft.ad 1.9.1 (latest version).

**Comment by Yannik** [comment]
I believe what's happening is the following:

If `identity` is not set, it is constructed using `CN={{ name }},{{ path }}` (path=defaultNamingContext if not defined) as described above. 
Relevant LOC: https://github.com/ansible-collections/microsoft.ad/blob/main/plugins/module_utils/_ADObject.psm1#L1104-L1113

Then, in `Get-AnsibleADObject`, if this `identity` matches regex `^.*\@.*\..*$`, it uses a LDAPFilter `(userPrincipalName=$($Matches[0]))` for the Get-ADObject call: https://github.com/ansible-collections/microsoft.ad/blob/main/plugins/module_utils/_ADObject.psm1#L715

This regex is extremely broad and matches anything that contains a @ symbol and a "." some place later in the string.
Including the `identity` that was constructed earlier, which is infact a DN and not a emailadress/UPN.

Specifically, in my example above the LDAPFilter looks like this: `(userPrincipalName=mygroup@example.net,cn=Users,dc=example,dc=net)`.

This is obviously does not return any matches.

Furthermore, the `group` objectClass does not even have a `userPrincipalName` attribute.

To fix this, I'd suggest:
* not ever filtering on userPrincipalName on objects that do not have that attribute (e.g. groups)
* only filter on userPrincipalName if the identity is actually a valid email-adress (and not a DN or just a samAccountName that happens to include a @ and "." char)

**Comment by jborean93** [comment]
Yep, using `name` will match by the LDAP name and not the various identities of the object. Using `identity` is the preferred way here, I'll look at the PR to solve the issue around matching with the UPN.

**Comment by Yannik** [comment]
> Yep, using `name` will match by the LDAP name and not the various identities of the object. Using `identity` is the preferred way here, I'll look at the PR to solve the issue around matching with the UPN.

Perhaps I didn't explain properly - the issue is not at all about the identity constructed from `name` being somehow problematic - the automatically generated DN is totally fine.

The problem also occurs when using `identity` explicitly with either samAccountName or DN due to the way it is determined whether `identity` contains a UPN - by simply checking if it contains an `@`-symbol: https://github.com/ansible-collections/microsoft.ad/blob/main/plugins/module_utils/_ADObject.psm1#L715. Which is not ideal since both DNs or samAccountNames can contain `@`-symbols as well - and it does that, even when userPrincipalName might not even me a valid attribute e.g. for groups.

Trying to match using identity with samAccountName 
```
    - microsoft.ad.group:
        name: mygroup@example.net
        identity: mygroup@example.net
        path: "cn=Users,dc=example,dc=net"
        scope: global
```

or using identity with CN

```
    - microsoft.ad.group:
        name: mygroup@example.net
        identity: CN=mygroup@example.net,cn=Users,dc=example,dc=net
        path: "cn=Users,dc=example,dc=net"
        scope: global
```

both of these fail.
