### ISSUE TITLE
module microsoft.ad.group not working

### ISSUE THREAD

**Issue by rebecucia1** [ansible-collections/microsoft.ad#201]
the creation of ActiveDirectory groups with module microsoft.ad.group is working fine, but if you try just to add users to an existing gorup it sais that the goup already exisit, what is normal, because it does :)

here the code example. the frist task is working perfecty and the gorup is being created, but the second one is always failling

```yaml
- name: Create group if it does not exists 
  microsoft.ad.group:
    name: "{{ folder_rights.stdout.split(';')[1] | regex_replace('\\r\\n')}}"
    scope: domainlocal
    path: OU=Groups,OU=Usuarios,OU=Castellana,DC=axa-seguros-es,DC=intraxa
    category: security
    attributes:
      set:
        description: "{{ item }}"  
        extensionAttribute1: "sync"
  when:  folder_rights.stdout.split(';')[0]  == "NoGroup"

- name: Add a domain user to the existing group
  microsoft.ad.group:
    name: "{{ folder_rights.stdout.split(';')[1] | regex_replace('\\r\\n')}}" 
    scope: domainlocal   
    members:
      add: 
        - "{{ share_user_list.split('\n') }}"
        - eat4643adm
        - "eat4643adm"
  when: 
    - folder_rights.stdout != "VariosGrupos\r\n"
    - folder_rights.stdout != "NoPath\r\n"
```

The output messaje is: 

```json
{
  "changed": false,
  "invocation": {
    "module_args": {
      "domain_server": null,
      "protect_from_deletion": null,
      "sam_account_name": null,
      "identity": null,
      "scope": "domainlocal",
      "category": null,
      "description": null,
      "domain_credentials": [],
      "state": "present",
      "domain_username": null,
      "path": null,
      "members": {
        "add": [
          [
            "eit6582adm"
          ],
          "eat4643adm"
        ],
        "set": null,
        "remove": null,
        "lookup_failure_action": "fail"
      },
      "managed_by": null,
      "domain_password": null,
      "attributes": {
        "add": {},
        "set": {},
        "remove": {}
      },
      "display_name": null,
      "homepage": null,
      "name": "GL_SE_AES_cert1_R"
    }
  },
  "distinguished_name": null,
  "object_guid": null,
  "msg": "New-ADGroup failed: The specified local group already exists",
  "_ansible_no_log": false
}
```
