### ISSUE TITLE
microsoft.ad.identity working example

### ISSUE THREAD

**Issue by ba31** [ansible-collections/microsoft.ad#26]
Please add the example of microsoft.ad.identity parameter. Its not clear in description how this should work and how it could change the sAMAccountName

**Comment by jborean93** [comment]
The `identity` field is only strictly necessary if you want to change the AD object name or path which are separate to the `sAMAccountName`. For example I have an AD user `CN=testuser,CN=Users,DC=domain,DC=test` with the `sAMAccountName` of `test1`. I do do the following to change the `sAMAccountName`.

```yaml
- microsoft.ad.user:
    name: testuser  # Matches the first CN=... and is what appears in dsa.msc
    state: present
    sam_account_name: test2
```

The `identity` parameter is used only for trying to find a user that does not match what `name` and `path` specify. For example you want to change the user's name from `testuser` to `otheruser`

```yaml
- microsoft.ad.user:
    name: otheruser
    identity: S-1-5-....  # Can be the objectGuid as well
    state: present
```

Instead of now creating a new user called `otheruser` it will modify the user object specified by `identity` to fit what is set there. I'll submit a PR to add an example of this but in your case it isn't needed for changing the `sAMAccountName`.
