### ISSUE TITLE
Manage AD Object Permissions

### ISSUE THREAD

**Issue by jiuka** [ansible-collections/microsoft.ad#39]
##### SUMMARY
We need to set/modify permissions on OUs and sometimes Groups. It would be nice to do this with ansible too. This includes enabling and disabling permission inheritance as well as add/set/remove of permisions. I am not sure if this should be a new module `microsoft.ad.acl` or should be integrated into ADObject.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`microsoft.ad.ou`, `microsoft.ad.group`, `microsoft.ad.user`, `microsoft.ad.object`, `microsoft.ad.computer`

##### ADDITIONAL INFORMATION

```yaml
- name: Ensure OU is protected
  microsoft.ad.acl:
    path: OU=AnsibleFest,DC=ansible,DC=local
    permissions:
      set:
        - group: Everyone
          rights: DeleteChild, DeleteTree, Delete
          type: deny
        - group: NT AUTHORITY\SYSTEM
          rights: GenericAll
        - group: NT AUTHORITY\ENTERPRISE DOMAIN CONTROLLERS
          rights: GenericRead
        - group: ANSIBLE\Domänen-Admins
          rights: GenericAll
        - group: ANSIBLE\AnsibleFestAdmins
          rights: CreateChild, DeleteChild
          object_type: bf967aba-0de6-11d0-a285-00aa003049e2
        - group: ANSIBLE\AnsibleFestAdmins
          rights: GenericAll
          inherited_object_type: bf967aba-0de6-11d0-a285-00aa003049e2
          inheritance: Descendents
```

```yaml
- name: Ensure OU is present & protected
  microsoft.ad.ou:
    name: AnsibleFest
    permissions:
      set:
        - group: Everyone
          rights: DeleteChild, DeleteTree, Delete
          type: deny
        - group: NT AUTHORITY\SYSTEM
          rights: GenericAll
        - group: NT AUTHORITY\ENTERPRISE DOMAIN CONTROLLERS
          rights: GenericRead
        - group: ANSIBLE\Domänen-Admins
          rights: GenericAll
        - group: ANSIBLE\AnsibleFestAdmins
          rights: CreateChild, DeleteChild
          object_type: bf967aba-0de6-11d0-a285-00aa003049e2
        - group: ANSIBLE\AnsibleFestAdmins
          rights: GenericAll
          inherited_object_type: bf967aba-0de6-11d0-a285-00aa003049e2
          inheritance: Descendents
```

**Comment by jborean93** [comment]
This is something that I was interesting in adding and while it might be nice to have it part of each module using a common set of rules it might potentially overload an already overloaded set of options. The other complications come from how to deal with the object type guids and inherited object type rules. It is certainly doable but it might take some time to come up with a sane solution here.

**Comment by guyomog78** [comment]
Well I just seen the #72 that in a good progress!

**Comment by abelal83** [comment]
Until there's a proper solution, I've come up with this as a temporary solution.

```
      - name: Run PowerShell script # noqa: run-once[task]
        run_once: true
        ansible.windows.win_powershell:
          script: |
            param (
              [PSCredential] $Credential,
              [string] $OU,
              [string] $UserOrGroup,
              [string] $Permission
            )

          # Get the security descriptor of the OU
          $OUObject = Get-ADOrganizationalUnit -Identity $OU -Properties nTSecurityDescriptor -Credential $Credential
          $SecurityDescriptor = $OUObject.nTSecurityDescriptor

          # Create a new access control entry (ACE)
          $ACE = New-Object System.DirectoryServices.ActiveDirectoryAccessRule(
              (New-Object System.Security.Principal.NTAccount($UserOrGroup)),
              [System.DirectoryServices.ActiveDirectoryRights]::$Permission,
              [System.Security.AccessControl.AccessControlType]::Allow
          )

          # Add the ACE to the security descriptor
          $SecurityDescriptor.AddAccessRule($ACE)

          # Apply the updated security descriptor to the OU
          Set-ADOrganizationalUnit -Identity $OU -Replace @{nTSecurityDescriptor = $SecurityDescriptor} -Credential $Credential

          Write-Host "$Permission permissions have been delegated to $UserOrGroup on $OU"

        parameters:
          OU: "{{ item.ou }}"
          UserOrGroup: "{{ item.member }}"
          Permission: "{{ item.permission }}"
        sensitive_parameters:
          - name: Credential
            username: "{{ domain_username }}"
            password: "{{ domain_password }}"
      loop:
        "{{ ad_ou_permissions }}"
```

and vars look like

```
ad_ou_permissions:
  - ou: "ou=Groups,ou=someou,{{ active_directory_root_path }}"
    member: MyDomain\abelal
    permission: GenericAll
```

It's by no means ideal as script only does append and no remove but it works for now and pretty sure I can work on it to handle absent.
