### ISSUE TITLE
microsoft.ad.user - having trouble updating user password

### ISSUE THREAD

**Issue by iamperson347** [ansible-collections/microsoft.ad#44]
##### SUMMARY
I'm attempting to update a service account (standard ad user, not a gmsa, etc.), but I'm having trouble getting this module to work as a replacement for win_domain_user. Ideally, I would like to pass in the sam account name of the service account, and update the password. 

- I have tried using the identity property exclusively (to initially find the object) but I receive an error that "name" is required.
- I have tried using the name property exclusively (to initially find the object) but I receive an error that account already exists. I'm assuming the module needs "path" in this case?
- I have tried using the identity and name property together, but this creates and issue where the module is trying to rename/move the ad user object.

The accounts will be in separate OU's, so I cannot hardcode the path. I do see an object_info module where I could query for the user object first, but it seems the ad.user module should be able to accomplish the task at hand (as it's a replacement for win_domain_user).

Do you have any suggestions on the use case above?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
microsoft.ad.user

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/opt/ansible-venv/5.10.0-core-2.12.10/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible-venv/5.10.0-core-2.12.10/lib/python3.8/site-packages/ansible
  ansible collection location = /opt/ansible-venv/5.10.0-core-2.12.10/share/ansible/collections
  executable location = /opt/ansible-venv/5.10.0-core-2.12.10/bin/ansible
  python version = 3.8.0 (default, Dec  9 2021, 17:53:27) [GCC 8.4.0]
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below
Collection   Version
------------ -------
microsoft.ad 1.2.0

```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/opt/ansible-venv/5.10.0-core-2.12.10/share/ansible/collections']
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/opt/ansible-venv/5.10.0-core-2.12.10/share/ansible/plugins/callback']
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/opt/ansible-venv/5.10.0-core-2.12.10/share/ansible/plugins/filter']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/inventory/running']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible/ansible.log
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/opt/ansible-venv/5.10.0-core-2.12.10/share/ansible/plugins/modules']

```

##### STEPS TO REPRODUCE
See summary above.

##### EXPECTED RESULTS

microsoft.ad.user can update user account passwords by passing in samaccountname similar to win_domain_user.

##### ACTUAL RESULTS

```paste below

```

**Comment by jborean93** [comment]
The `name` value of `microsoft.ad.user` is slightly different from `win_domain_user` as the latter was slightly confusing as to how it worked with `name` acting as both the `cn`/`name` of the user account as well as having a fallback on the `sAMAccountName` and other values. It made supporting renaming/moving the object a lot harder to achieve whereas `microsoft.ad.user` follows a set standard used by all the modules in this collection.

A basic description is that `name` is always referring to the `CN` component of the user's distinguished name. An example of this:

```yaml
- name: manages user CN=testing,{{ default_domain_user_container}}
  microsoft.ad.user:
    name: testing

- name: manages user CN=testing,OU=MyOU,DC=domain,DC=test
  microsoft.ad.user:
    name: testing
    path: OU=MyOU,DC=domain,DC=test
```

If `identity` is not used then it will either manage the user at the path set or create a new user if it does not. Unfortunately even if `identity` is set to refer to the user to manage, I believe it will try and move the user to the target path which if no `path` was specified will be the default user container. So:

```yaml
- name: manages sAMAccountName userSAM and ensures it is at CN=testing,{{ default_domain_user_container}} 
  microsoft.ad.user:
    name: testing
    identity: userSAM

- name: manages sAMAccountName userSAM and ensures it is at CN=testing,OU=MyOU,DC=domain,DC=test
  microsoft.ad.user:
    name: testing
    identity: userSAM
    path: OU=MyOU,DC=domain,DC=test
```

I see two possible options:

1. Keep the existing behaviour and require the `path` be set correctly in this situation
2. Change the behaviour to only move if a `path` was explicitly set

I am leaning towards option 2 because it closely matches the behaviour of `win_domain_user`. I do need to try and consider whether it might have some unintended side effects I can't think off right now. Maybe supporting a difference between no value/null (do not move) and an empty string for `path` (move to the default path) might help?
