### ISSUE TITLE
microsoft.ad.user failed due to "protect_from_deletion" parameter as "ProtectedFromAccidentalDeletion" cannot be found

### ISSUE THREAD

**Issue by caidingyu** [ansible-collections/microsoft.ad#58]
##### SUMMARY

Failed to update AD user accounts with `microsoft.ad.user` module by adding `protect_from_deletion` parameter. Got error message: `A parameter cannot be found that matches parameter name 'ProtectedFromAccidentalDeletion'.`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`microsoft.ad.user`

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.2]
  config file = /Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg
  configured module search path = ['/Users/ericca/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ericca/sources/OrionHealth/nzms-ansible/.venv/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/ericca/sources/OrionHealth/nzms-ansible/galaxy/collections
  executable location = /Users/ericca/sources/OrionHealth/nzms-ansible/.venv/bin/ansible
  python version = 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Users/ericca/sources/OrionHealth/nzms-ansible/.venv/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection   Version
------------ -------
microsoft.ad 1.2.0
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg) = ['/Users/ericca/sources/OrionHealth/nzms-ansible/galaxy/collections']
CONFIG_FILE() = /Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg
DEFAULT_ROLES_PATH(/Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg) = ['/Users/ericca/sources/OrionHealth/nzms-ansible/galaxy/roles']
DEFAULT_TIMEOUT(/Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg) = 30
DEPRECATION_WARNINGS(/Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg) = False
PAGER(env: PAGER) = less
RETRY_FILES_ENABLED(/Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Target host: 
* OS: Microsoft Windows Server 2019 Datacenter
* PowerShell:
```
PS C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.4644
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.4644
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

AD: AWS managed Active Directory
* OS: Windows Server 2019

Ansible master host: 
* OS: Mac OS Ventura 13.5 arm64 Darwin Kernel Version 22.6.0

##### STEPS TO REPRODUCE

```yaml
- name: Ensure service AD accounts exist
  microsoft.ad.user:
    name: "{{ item.name }}"
    upn: "{{ item.name }}@{{ ad_domain }}"
    firstname: "{{ item.name }}"
    password: "{{ item.password }}"
    description: "{{ item.description }}"
    path: "OU=Users,{{ ad_root_ou }}"
    state: present
    groups:
      add: "{{ item.groups | default([]) }}"
    update_password: when_changed
    password_never_expires: "{{ item.password_never_expires | default(omit) }}"
    user_cannot_change_password: "{{ item.user_cannot_change_password | default(omit) }}"
    spn:
      set: "{{ item.spn | default([]) }}"
    email: "{{ NZMS_email }}"
    domain_server: "{{ ad_domain }}"
    protect_from_deletion: true
    loop: "{{ service_ad_accounts }}"
```
Added `protect_from_deletion: true` into above existing task and run Ansible playbook to update the existing AD user accounts.

##### EXPECTED RESULTS

The AD user accounts could be updated successfully by adding `protect_from_deletion: true`.

##### ACTUAL RESULTS

Update failed with error message:
```
A parameter cannot be found that matches parameter name 'ProtectedFromAccidentalDeletion'.
At line:1091 char:66
+ ...       $finalADObject = & $setCommand @commonParams @setParams @adPara ...
+                                                        ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-ADUser], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.ActiveDirectory.Management.Commands.SetADUser

ScriptStackTrace:
at Invoke-AnsibleADObject, <No file>: line 1091
at <ScriptBlock>, <No file>: line 458
```

```paste below

```
