### ISSUE TITLE
microsoft.ad.inventory connecting to port 22 and not ldap

### ISSUE THREAD

**Issue by manishingole** [ansible-collections/microsoft.ad#71]
##### SUMMARY
I have created inventory file with name microsoft.ad.ldap.yml. I added server details of microsoft active directory. Created self sign certificate. Created ansible playbook to create group in active directory with microsoft.a.group module. When I run ansible playbook by refering microsoft.ad.ldap.yml as inventory it is connecting over port 22 and not ldap

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

microsoft.ad.inventory
##### ANSIBLE VERSION

```paste below
2.15.3
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Alpine Linux

##### STEPS TO REPRODUCE

created file microsoft.ad.ldap.yml
```yaml
plugin: microsoft.ad.ldap

server: ad-ip
tls_mode: ldaps
username: user@domain.com
password: password
auth_protocol: ntlm
certificate: cert.crt
certificate_key: cert.key
certificate_password: "password"
cert_validation: "ignore"
search_base: OU=Users,DC=name1,DC=name2,DC=com

attributes:
  sAMAccountName:
    sam_account_name:
  objectSid:
    computer_sid:
  pwdLastSet:
    password_last_set: this | microsoft.ad.as_datetime
  comment:
    host_comment
  memberOf:
    computer_membership: this | map("regex_search", '^CN=(?P<name>.+?)((?<!\\),)', '\g<name>') | flatten 
```

created playbook yml file with microsoft.ad.group module
run ansible playbook ansible-playbook -i microsoft.ad.ldap.yml playbook name -e 'variable=value'

```yaml
---
- name: Execute Command on Remote Windows Machine
  hosts: localhost  # Replace 'windows_hosts' with the group or host where your Windows machines are defined.
  gather_facts: no     # Disable gathering facts as it's not required for this playbook.
  ignore_unreachable: true
  tasks:
    - name: Add group and specify the AD domain services to use for the create
      microsoft.ad.group:
        name: "{{ permission_set_name | lower }}"
        scope: global
        category: security
        state: present
      delegate_to: <ad-ip> 
      register: result   # Store the output of the command in the 'result' variable.

    - name: Display Command Output
      debug:
        var: result.stdout_lines   # Print the standard output of the executed command.
```

##### EXPECTED RESULTS

Connect to active directory and create group
##### ACTUAL RESULTS

connecting over port 22 and timing out
msg": "Unable to execute ssh command line on a controller due to: [Errno 2] No such file or directory: b'ssh'"

```paste below

```

**Comment by jborean93** [comment]
You still need to provide the variables Ansible needs to connect to a Windows host. Without any of those it is going to use the default host settings which is ssh. You have a few options available to you;

## Set the host options inline

```yaml
... # All your existing settings

compose:
  ansible_connection: '"winrm"'  # Can be psrp, etc
  ... # Other host vars to set for each host found
```

When the inventory is run it will also apply these static values to the host allowing you to change whatever you need. Please note the inner value needs to be quoted hence why it is quoted with single quotes then double quotes. This is because the value is templated so the raw value being being templated needs quotes.

## Pair with static inventory/group_vars file

I personally prefer this option where you pair the dynamic inventory with a static inventory. In your dynamic inventory setup you can have

```yaml
... # Same as before

groups:
  windows: true
```

Then you can have an `inventory.ini` with the following

```ini
[windows:vars]
ansible_connection=winrm
ansible_port=5985
...
```

You could even place these settings inside `group_vars/windows.yml` if you don't need another inventory for static hosts and just want to apply these settings.

Now with this the hosts being found are automatically added to the `windows` group and Ansible will combine those static settings. You can even set the `ansible.cfg` to run both inventories by default

```ini
[defaults]
inventory microsoft.ad.ldap.yml, inventory.ini
```
