### ISSUE TITLE
microsoft.ad.membership add reboot timeout option

### ISSUE THREAD

**Issue by markatdxb** [ansible-collections/microsoft.ad#78]
##### SUMMARY

Would be great to add option in this module to set the reboot timeout. Currently when joining physical servers to domain im getting module errors due to reboot timeout
Its not a big deal as i can work around it by not using this option and instead using the standard reboot module - just an idea 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

microsoft.ad.membership

##### ADDITIONAL INFORMATION

 "msg": "Timed out waiting for last boot time check (timeout=600)",

```yaml
{
    "changed": true,
    "msg": "Failed to reboot after module returned reboot_required, see reboot_result and module_result for more details",
    "reboot_result": {
        "changed": true,
        "elapsed": 605,
        "failed": true,
        "unreachable": false,
        "rebooted": true,
        "msg": "Timed out waiting for last boot time check (timeout=600)",
        
    },
    "module_result": {
        "changed": true,
        "reboot_required": true
    },
    "invocation": {
        "module_args": {
            "reboot": true,
            "dns_domain_name": "domain",
            "domain_admin_user": "domain_admin",
            "offline_join_blob": null,
            "domain_admin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "workgroup_name": null,
            "state": "domain",
            "hostname": "server1",
            "domain_ou_path": null
        }
    },
    "_ansible_no_log": null,
    "_ansible_delegated_vars": {
        "ansible_host": "10.10.10.10",
        "ansible_port": 5986,
        "ansible_user": "{{ username }}",
        "ansible_connection": "winrm"
    }
}
```
