### ISSUE TITLE
Adding members to a group requires an explicit path to be set

### ISSUE THREAD

**Issue by timstipdonk** [ansible-collections/microsoft.ad#87]
##### SUMMARY
When using version 1.1 of the module, the microsoft.ad.group module returns an access denied, unless a "Path" variable is defined. I suspect that the module tries to move the specific AD group. When the "Path" variable is added, the code works as expected, and adds the user to the AD group.

The task is delegated to a server with the correct AD tools, and has been verified to work correctly with the usage of the previous module (community.windows.win_domain_group). The username and password are also correct and verified using the community.windows.win_domain_group module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

microsoft.ad.group

##### ANSIBLE VERSION

```
ansible [core 2.15.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.18 (main, Sep 22 2023, 17:58:34) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection   Version
------------ -------
microsoft.ad 1.1.0

```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

Target OS is a mix of 2019 and 2022 servers, behavior does not change between them.

##### STEPS TO REPRODUCE

The following code fails, and returns an error (see screenshot below the ansible code). When the Path variable is added, the playbook seems to work as expected.
  
![image](https://github.com/ansible-collections/microsoft.ad/assets/23154695/863c971c-9e16-4801-bc77-6d269870ae93)

    

```yaml
- name: Add user's AD- account to group membership
  microsoft.ad.group:
    name: "AD-Group-Name"
    members:
      add:
      - "{{ form_username }}"
    scope: global
    category: security
    domain_username: "{{ domain_username }}"
    domain_password: "{{ domain_password }}"
  delegate_to: "{{ delegation_server_win }}"
  vars:
    ansible_user: "{{ ansible_user }}"
    ansible_password: "{{ ansible_password }}"
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: kerberos
```

##### EXPECTED RESULTS

User added to group

##### ACTUAL RESULTS

Received the following fatal error:

![image](https://github.com/ansible-collections/microsoft.ad/assets/23154695/8e71ce98-4858-4f2d-9185-caf74b5206c0)

```paste below
FAILED! => {"changed": false, "distinguished_name": null, "msg": "New-ADGroup failed: Access is denied", "object_guid": null}
```

**Comment by jborean93** [comment]
You might need to update to a newer version and use the `identity` option instead of `name`. Currently if you specify `name` without a `path` it will attempt to find the LDAP object with that name in the default path which is why it's trying to use `New-ADGroup` to create it. Since v1.4.0 you can use `identity` to find a group by the `sAMAccountName` and manage it that way https://github.com/ansible-collections/microsoft.ad/blob/main/CHANGELOG.rst#minor-changes

```yaml
- name: Add user's AD- account to group membership
  microsoft.ad.group:
    identity: "AD-Group-Name"
    members:
      add:
      - "{{ form_username }}"
    scope: global
    category: security
    domain_username: "{{ domain_username }}"
    domain_password: "{{ domain_password }}"
  delegate_to: "{{ delegation_server_win }}"
  vars:
    ansible_user: "{{ ansible_user }}"
    ansible_password: "{{ ansible_password }}"
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: kerberos
```
