### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by marksie1988** [ansible-collections/microsoft.ad#88]
##### SUMMARY

Trying to join a number of Windows server 2022 to  a test domain and they all keep failing saying "the system cannot find the file specified.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

microsoft.ad.membership

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
```

##### COLLECTION VERSION

```paste below
Collection   Version
------------ -------
microsoft.ad 1.4.1
```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = ['/home/user/repos/lab/ansible/roles~']
HOST_KEY_CHECKING(/home/user/repos/lab/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Server 2022

##### STEPS TO REPRODUCE

I am using the following play: 

```yaml
    - name: Join members to domain
      microsoft.ad.membership:
        dns_domain_name: "{{ dns_domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        domain_ou_path: "{{ domain_join_ou_path }}"
        state: domain
        reboot: true
```

with these groupvars:

```yaml
dns_domain_name: "lab.com"
domain_netbios_name: "LAB"
domain_admin_user: "administrator@lab.com"
domain_admin_password: "mypassword"
domain_join_ou_path: "OU=Windows,OU=Servers,DC=lab,DC=com"
```

##### EXPECTED RESULTS

Servers should be joined to the domain

##### ACTUAL RESULTS

```paste below
The full traceback is:
Computer 'sql-1' failed to join domain 'lab.com' from its current workgroup 'WORKGROUP' with following error message: The system cannot find the file specified.
At line:210 char:13
+             Add-Computer @joinParams
+             ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (sql-1:String) [Add-Computer], InvalidOperationException
    + FullyQualifiedErrorId : FailToJoinDomainFromWorkgroup,Microsoft.PowerShell.Commands.AddComputerCommand

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 210
fatal: [sql-1]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Computer 'sql-1' failed to join domain 'raxlab.com' from its current workgroup 'WORKGROUP' with following error message: The system cannot find the file specified."
}
```
