### ISSUE TITLE
Add action_groups

### ISSUE THREAD

**Issue by peterbaumert** [ansible-collections/microsoft.ad#93]
##### SUMMARY
Add action groups so one can specify username, password etc. only once

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
meta/runtime.yml

##### ADDITIONAL INFORMATION

domain_server would be specified once and then used by all following commands

```yaml
- name: Check Active Directory
  delegate_to: <win-host>
  module_defaults:
    group/microsoft:
        domain_server: "{{ domain_server }}"
        domain_username: "{{ domain_username }}"
        domain_password: "{{ domain_password }}"
  vars:
    ansible_connection: ssh
    ansible_shell_type: cmd
  block:
    - name: Ensure OU is present & protected
      microsoft.ad.ou:
        name: Fancy_OU
        path: OU=Permissions,OU=Groups,DC=example,DC=com
        state: present
        protect_from_deletion: true

    - name: Ensure other OU is present & protected
      microsoft.ad.ou:
        name: Fancy_OU2
        path: OU=Permissions,OU=Groups,DC=example,DC=com
        state: present
        protect_from_deletion: true
```

**Comment by peterbaumert** [comment]
Maybe something like

```yaml

action_groups:
  microsoft:
  - computer
  - debug_ldap_client module
  - domain
  - domain_controller
  - membership
  - object
  - object_info
  - offline_join
  - ou
  - user
```
